name: Tests

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Execute Tests
        working-directory: ./App
        run : |
          npm ci
          npm run test
